# Change these first
owner: WhatTheHost-Dev # Your GitHub organization or username, where this repository lives
repo: Status # The name of this repository

sites:
  - name: WhatTheHost Webseite
    url: https://www.whatthehost.de
    icon: https://www.whatthehost.de/assets/favicons/favicon-192.png
  - name: WhatTheHost Forum
    url: https://community.whatthehost.de
    icon: https://www.whatthehost.de/assets/favicons/favicon-192.png
  - name: WhatTheHost Plesk Host
    url: $PH1
    icon: https://www.whatthehost.de/assets/favicons/favicon-192.png

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.whatthehost.de
  favicon: https://www.whatthehost.de/assets/favicons/favicon-192.png
  # baseUrl: /your-repo-name
  logoUrl: https://www.whatthehost.de/assets/favicons/favicon-192.png
  name: WhatTheHost Status
  introTitle: "Willkommen auf unserer Status Seite von **WhatTheHost**!"
  introMessage: Hier findest du aktuelle Störungen unserer Dienstleistungen.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/WhatTheHost-Dev

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
