# Change these first
owner: WhatTheHost-Dev # Your GitHub organization or username, where this repository lives
repo: Status # The name of this repository

sites:
  - name: Webseite
    url: https://www.whatthehost.de
    icon: https://www.whatthehost.de/assets/favicons/favicon-192.png
  - name: Dashboard
    url: https://dashboard.whatthehost.de
    icon: https://www.whatthehost.de/assets/favicons/favicon-192.png
  - name: Livechat
    url: $CHAT
    icon: https://www.whatthehost.de/assets/favicons/favicon-192.png
  - name: Forum
    url: https://community.whatthehost.de
    icon: https://www.whatthehost.de/assets/favicons/favicon-192.png
  - name: Plesk Host 1
    url: $PH1
    icon: https://www.whatthehost.de/assets/favicons/favicon-192.png
  - name: Game Panel
    url: $GP
    icon: https://www.whatthehost.de/assets/favicons/favicon-192.png
  - name: Game Host 1
    check: "tcp-ping"
    url: $GH1
    port: $GH1_P
    icon: https://www.whatthehost.de/assets/favicons/favicon-192.png

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.whatthehost.de
  favicon: https://www.whatthehost.de/assets/favicons/favicon-192.png
  # baseUrl: /your-repo-name
  logoUrl: https://www.whatthehost.de/assets/favicons/favicon-192.png
  name: WhatTheHost Status
  introTitle: "Willkommen auf unserer Status Seite von **WhatTheHost**!"
  introMessage: Hier findest du aktuelle Störungen unserer Dienstleistungen.
    
  navbar:
    - title: Webseite
      href: https://www.whatthehost.de/
    - title: Status
      href: /
    - title: Discord
      href: https://discord.gg/vcPEWQt
      
NOTIFICATION_EMAIL_SMTP: true
NOTIFICATION_EMAIL_SMTP_PORT: 587
NOTIFICATION_EMAIL_SMTP_HOST: $PH1
NOTIFICATION_EMAIL_SMTP_USERNAME: $E_MAIL_USERNAME
NOTIFICATION_EMAIL_SMTP_PASSWORD: $E_MAIL_PASSWORD

NOTIFICATION_EMAIL: true
NOTIFICATION_EMAIL_FROM: $E_MAIL_USERNAME
NOTIFICATION_EMAIL_TO: $E_MAIL_NOTIFICATION_ADDRESS

i18n:
  activeIncidents: Aktive Vorfälle
  allSystemsOperational: Alle Systeme sind in Ordnung
  incidentReport: "Vorfall bericht #$NUMBER →"
  activeIncidentSummary: Geöffnet am $DATE mit $POSTS Beiträgen
  incidentTitle: Vorfall $NUMBER Details
  incidentDetails: Vorfalldetails
  incidentFixed: Gelöst
  incidentOngoing: Laufend
  incidentOpenedAt: Geöffnet um
  incidentClosedAt: Geschlossen um
  incidentSubscribe: Abonniere für updates
  incidentViewOnGitHub: Auf GitHub ansehen
  incidentCommentSummary: Veröffentlicht am $DATE von $AUTHOR
  incidentBack: ← Zurück zu allen Vorfällen
  pastIncidents: Vergangene Vorfälle
  pastIncidentsResolved: Gelöst in $MINUTES Minuten mit $POSTS Beiträgen
  liveStatus: Live-Status
  overallUptime: "Gesamtbetriebszeit: $UPTIME"
  overallUptimeTitle: Gesamtbetriebszeit
  averageResponseTime: "Durchschnittliche Reaktionszeit: $TIMEms"
  averageResponseTimeTitle: Durchschnittliche Reaktionszeit
  sevelDayResponseTime: 7 Tage Reaktionszeit
  responseTimeMs: Reaktionszeit (ms)
  up: Erreichbar
  down: Nicht Erreichbar
  degraded: Beeinträchtigt
  ms: ms
  loading: Wird geladen
  navGitHub: GitHub
  footer: Diese Seite ist [Open Source]($REPO), unterstützt von [Upptime](https://upptime.js.org)
  rateLimitExceededTitle: Rate limit exceedeed
  rateLimitExceededIntro: You have exceeded the number of requests you can do in an hour, so you'll have to wait before accessing this website again. Alternately, you can add a GitHub Personal Access Token to continue to use this website.
  rateLimitExceededWhatDoesErrorMean: What does this error mean?
  rateLimitExceededErrorMeaning: This website uses the GitHub API to access real-time data about our websites' status. By default, GitHub allows each IP address 60 requests per hour, which you have consumed.
  rateLimitExceededErrorHowCanFix: How can I fix it?
  rateLimitExceededErrorFix: You can wait for another hour and your IP address' limit will be restored. Alternately, you can add your GitHub Personal Access Token, which gives you an additional 5,000 requests per hour.
  rateLimitExceededGeneratePAT: Learn how to generate a Personal Access Token
  rateLimitExceededHasSet: You have a personal access token set.
  rateLimitExceededRemoveToken: Remove token
  rateLimitExceededGitHubPAT: GitHub Personal Access Token
  rateLimitExceededCopyPastePAT: Copy and paste your token
  rateLimitExceededSaveToken: Save token
  errorTitle: An error occurred
  errorIntro: An error occurred in trying to get the latest status details.
  errorText: You can try again in a few moments.
  errorHome: Go to the homepage
  pastScheduledMaintenance: Vergangene geplante Wartung
  scheduledMaintenance: Geplante Wartung
  scheduledMaintenanceSummaryStarted: Gestartet am $DATE für $DURATION Minuten
  scheduledMaintenanceSummaryStarts: Beginnt am $DATE für $DURATION Minuten
  startedAt: Fing an bei
  startsAt: Startet um
  duration: Dauer
  durationMin: $DURATION Minuten
  incidentCompleted: Vollendet
  incidentScheduled: Geplant

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
